language: php
php:
    - 5.6
branches:
    except:
        - feature/free-order
        - presenters
git:
    submodules: false
before_script:
    - sh -c "composer global require 'phpunit/phpunit=3.7.33'"
    - sh -c "ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit ./Vendor/PHPUnit"
